//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeCardGamesAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        public static Settings Default
        {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
            get {
                return defaultInstance;
            }
        }
    }
}
